require.config({
	baseUrl:'/js/',
	paths:{
		'mui':'libs/mui.min',
		'picker':'libs/mui.picker.min',
		'poppicker':'libs/mui.poppicker',
		'getuid':'utils/getuid'
	},
	shim:{
		'picker':{
			deps:['mui']
		}
	}
});